services:  
  - type: web    
    name: django-web-service    
    env: python    
    plan: free    
    buildCommand: "pip install -r requirements.txt"    
    startCommand: "gunicorn render_deploy.wsgi --log-file -"